from daily_paper.render import render_markdown


def test_render_markdown_smoke() -> None:
    report = {
        "report_type": "daily_paper_digest",
        "report_date": "2026-04-14",
        "timezone": "Asia/Shanghai",
        "generated_at": "2026-04-14T23:45:00+08:00",
        "generator": {"repo_name": "demo", "repo_commit": "abc", "pipeline_version": "v1"},
        "sources": [{"name": "arXiv", "enabled": True, "query_groups": ["VLA"]}],
        "crawl_window": {"start": "2026-04-13T00:00:00+08:00", "end": "2026-04-14T23:59:59+08:00", "note": "demo"},
        "statistics": {"raw_candidates_total": 1, "deduplicated_total": 1, "selected_total": 1, "highlights_total": 1},
        "topic_counts": {"vla": 1, "world_models": 0, "multimodal_llm": 0, "agents": 0, "other_relevant": 0},
        "selection_policy": {"included_if": ["x"], "excluded_if": ["y"]},
        "ranking_policy": {"highlight_score_formula": "demo", "score_range": "0-5"},
        "tags": ["daily-digest"],
        "executive_summary": {
            "conclusion_lines": ["demo"],
            "top_highlights": [{"title": "paper", "reason": "demo"}],
            "research_observations": [{"label": "趋势 1", "text": "demo"}],
        },
        "metadata_summary": {
            "report_date": "2026-04-14",
            "timezone": "Asia/Shanghai",
            "generated_at": "2026-04-14T23:45:00+08:00",
            "raw_candidates_total": 1,
            "deduplicated_total": 1,
            "selected_total": 1,
        },
        "query_groups": ["VLA"],
        "query_terms": {"VLA": ["vision-language-action"]},
        "topic_overview": [{"name": "VLA", "count": 1, "judgement": "demo", "top_papers": ["paper"], "commonalities": ["planning"], "pitfalls": ["demo"]}],
        "highlight_papers": [
            {
                "paper_id": "arxiv-1",
                "title": "paper",
                "authors": ["a"],
                "first_author": "a",
                "source_primary": "arXiv",
                "source_aliases": ["arXiv / VLA"],
                "arxiv_id": "2604.00001",
                "version": "v1",
                "hf_paper_url": None,
                "paper_url": "https://arxiv.org/abs/2604.00001",
                "pdf_url": "https://arxiv.org/pdf/2604.00001.pdf",
                "project_url": None,
                "code_url": None,
                "model_url": None,
                "dataset_url": None,
                "demo_url": None,
                "published_at": "2026-04-14T00:00:00+08:00",
                "updated_at": "2026-04-14T00:00:00+08:00",
                "primary_category": "cs.RO",
                "categories": ["cs.RO"],
                "institution_hint": None,
                "license_hint": None,
                "comment": None,
                "journal_ref": None,
                "doi": None,
                "summary": "demo",
                "topics": ["VLA"],
                "primary_topic": "VLA",
                "query_groups": ["VLA"],
                "method_tags": ["planning"],
                "application_tags": ["robot manipulation"],
                "one_line_summary": "demo",
                "why_read_today": "demo",
                "relevance_level": "direct",
                "highlight_score": 4.2,
                "recommended_action": "read_now",
                "topic_scores": {"VLA": 4.2},
                "structured_summary": {
                    "problem": "demo",
                    "motivation": "demo",
                    "core_idea": "demo",
                    "method": "demo",
                    "training": "demo",
                    "inference": "demo",
                    "evaluation": "demo",
                    "main_results": "demo",
                    "claim": "demo",
                },
                "novelty_points": ["demo"],
                "strengths": ["demo"],
                "weaknesses": ["demo"],
                "assumptions": ["demo"],
                "risks": ["demo"],
                "open_questions": ["demo"],
                "relation_to_prior_work": "demo",
                "domain_analysis": {
                    "vla": {"embodiment": "unknown", "action_space": "unknown", "control_level": "unknown", "memory_usage": "unknown", "planner_usage": "no", "reasoner_usage": "no", "world_model_usage": "no", "real_robot": "no", "simulator": "null", "data_source": "unknown"},
                    "world_models": {"state_representation": "unknown", "prediction_target": "unknown", "horizon": "unknown", "planning_interface": "unknown", "control_coupling": "unclear"},
                    "multimodal_llms": {"modalities": ["text"], "reasoning_type": "none", "long_context_usage": "no", "grounding_method": "none"},
                    "agents": {"agent_type": "unknown", "tooling": "unknown", "memory_type": "none", "planning_style": "unknown", "verification_style": "no verifier"},
                },
                "reproducibility": {"code_available": False, "weights_available": False, "dataset_available": False, "env_instructions_available": False, "repro_effort_estimate": "high"},
                "my_take": {"should_i_read_it": "是", "should_i_reproduce_it": "条件满足时再看", "what_can_i_borrow": "planning", "what_do_i_not_buy": "demo", "best_use_case": "robot manipulation"},
                "hf_upvotes": None,
                "hf_ai_summary": None,
                "hf_ai_keywords": [],
                "submitted_on_daily_at": None,
            }
        ],
        "paper_list_by_topic": {"VLA": []},
        "cross_paper_insights": {"trends": ["demo"], "motifs": {"planning": "demo"}, "gaps": ["demo"], "inspiration": ["demo"]},
        "action_queue": {"read_now": [{"title": "paper", "reason": "demo"}], "track": [], "reproduce": [], "ignore": []},
        "appendix": {"raw_candidates": [{"title": "paper", "source": "arXiv", "topic": "VLA"}], "filtered_out": [], "deduplication_log": [], "crawl_errors": [], "parsing_warnings": [], "todo_for_tomorrow": ["demo"]},
    }
    rendered = render_markdown(report)
    assert "Daily Research Digest" in rendered
    assert "paper" in rendered
